server:
  port: 8764
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: gateway
  jmx:
    default-domain: gateway
  cloud:
    config:
      enabled: false
  sleuth:
    sampler:
      percentage: 1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: false


info:
  app:
    name: gateway
    description: gateway
    version: 1.0.0
hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: false #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
      isolation:
        thread:
          timeoutInMilliseconds: 60000 #断路器超时时间，默认1000ms
#feign:
#  hystrix:
#    enabled: false

ribbon:
  ReadTimeout: 60000 #负载均衡超时时间，默认值5000
  ConnectTimeout: 60000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1
  #OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
zuul:
  max:
    host:
      connections: 6000
  host:
    maxTotalConnections: 10000
    maxPerRouteConnections: 10000
    socket-timeout-millis: 60000 #默认1000
    connect-timeout-millis: 60000 #默认2000
  semaphore:
    max-semaphores: 200
  servlet-path: /
  sensitiveHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8763/eureka  #注册 中心已经开启认证
      #defaultZone: http://admin:123456@119.23.133.182:8761/eureka  #注册 中心已经开启认证
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: /swagger-ui.html
    prefer-ip-address: true #IP显示
    lease-renewal-interval-in-seconds: 10    # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒）


filter:
  exclude-path: poserver.do,/download,/outputDocument/edit/get,/downloadByFileid,/outputDocument/edit/save,/outputDocument/edit/editWordSave,/outputDocument/edit/editAnaSave,/wechat/login/public/mobileLogin,/wechat/login/public/accountLogin,/pc/public/login,/wechat/login/safetyVerification,/wechat/login/public/changepwd,/wechat/login/public/get/contact,/wechat/login/public/register,/wechat/login/public/getFaceVerifyUrl,/wechat/login/public/getFaceVerifyInfo,/wechat/login/getVerify,/wechat/login/support,/pc/login,/fileservice,/image/get/graphicCode,ixm/wechat/get/citizen/login/address,/wx/get/openId,/ixm/wechat/login,/support/standParaQuery/getCodeVo,/support/standParaQuery/getParaValue,/controlDownload/get/list,/controlDownload/downLoadFile,/ixm/pc/login,/ixm/pc/get/citizen/login/address,/statistics/export/downLoadExcelFile,/outputDocument/edit/editWordSave,/analysis/document/docDownLoad,/captcha/code,/outputDocument/edit/printWordSave,/ixm/citizen/wx/logout,/wechat/mini/login/video/accountLogin,/caseCirculation/receive/info,/caseCirculation/sendBack/info,/caseCirculation/response/info,/caseCirculation/response/file,/workbench/checkSelectCaseInfo,/mps-platform-web
